# Generated by Django 3.2 on 2021-04-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_rename_profile_pic_userprofile_profile_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
    ]
